### ISSUE TITLE
Cannot run gobar with the code snippet mentioned in the readme.md file.

### ISSUE THREAD

**Issue by 231tr0n** [distatus/gobar#2]
```bash
while :; do date; sleep 1; done | ./gobar
```
I am getting this error when trying to run this command
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
main.(*Bar).Draw(0xc0000aa000, {0xc0001220a0, 0x1, 0x0?})
	/home/xeltron/go/pkg/mod/github.com/distatus/gobar@v0.0.0-20160515203426-c6268c4216f5/gobar.go:345 +0xb98
main.main()
	/home/xeltron/go/pkg/mod/github.com/distatus/gobar@v0.0.0-20160515203426-c6268c4216f5/gobar.go:565 +0x4b0

```
Can you please help me figure out what is the issue I am facing with while running this bar?

**Comment by KenjiTakahashi** [comment]
Indeed you're right.
That's because it cannot find any font definitions.
You'll have to specify at least 1 font file with the `-fonts` flag and then it should work.

I think I have written that on assumption the it will be able to find a suitable font on it's own, but never got around to writing the code for this. It seems some other people have written libs for that in the meantime, I might want to revisit the idea soon(-ish).

**Comment by KenjiTakahashi** [comment]
Should work as expected now.

**Comment by 231tr0n** [comment]
Yup it works now thanks a lot.
